Rand index

In [ ]:
from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]
metrics.rand_score(labels_true, labels_pred)

0.6666666666666666

In [ ]:
metrics.adjusted_rand_score(labels_true, labels_pred)

0.24242424242424243

In [ ]:
labels_pred = [1, 1, 0, 0, 3, 3]
metrics.rand_score(labels_true, labels_pred)


0.6666666666666666

In [ ]:
metrics.adjusted_rand_score(labels_true, labels_pred)

0.24242424242424243

In [ ]:
metrics.rand_score(labels_pred, labels_true)


0.6666666666666666

In [ ]:
metrics.adjusted_rand_score(labels_pred, labels_true)


0.24242424242424243

In [ ]:
labels_pred = labels_true[:]
metrics.rand_score(labels_true, labels_pred)

1.0

In [ ]:
metrics.adjusted_rand_score(labels_true, labels_pred)


1.0

In [ ]:
labels_true = [0, 0, 0, 0, 0, 0, 1, 1]
labels_pred = [0, 1, 2, 3, 4, 5, 5, 6]
metrics.rand_score(labels_true, labels_pred)

0.39285714285714285

In [ ]:
metrics.adjusted_rand_score(labels_true, labels_pred)


-0.07207207207207207

Mutual Information based scores

In [ ]:

from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]

In [ ]:
metrics.adjusted_mutual_info_score(labels_true, labels_pred)  

0.2987924581708901

In [ ]:
labels_pred = [1, 1, 0, 0, 3, 3]
metrics.adjusted_mutual_info_score(labels_true, labels_pred)  


0.2987924581708901

In [ ]:
metrics.adjusted_mutual_info_score(labels_pred, labels_true) 

0.2987924581708903

In [ ]:
labels_pred = labels_true[:]
metrics.adjusted_mutual_info_score(labels_true, labels_pred)  

1.0

In [ ]:
metrics.normalized_mutual_info_score(labels_true, labels_pred)  


1.0

In [ ]:
metrics.mutual_info_score(labels_true, labels_pred)  


0.6931471805599452

In [ ]:
labels_true = [0, 1, 2, 0, 3, 4, 5, 1]
labels_pred = [1, 1, 0, 0, 2, 2, 2, 2]
metrics.adjusted_mutual_info_score(labels_true, labels_pred)  

-0.16666666666666655

Homogeneity, completeness and V-measure

In [ ]:
from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]

metrics.homogeneity_score(labels_true, labels_pred)


0.6666666666666669

In [ ]:
metrics.completeness_score(labels_true, labels_pred)

0.420619835714305

In [ ]:
metrics.v_measure_score(labels_true, labels_pred)

0.5158037429793889

In [ ]:
metrics.v_measure_score(labels_true, labels_pred, beta=0.6)

0.5467344787062375

In [ ]:
metrics.v_measure_score(labels_true, labels_pred, beta=1.8)

0.48447946234141737

In [ ]:
metrics.homogeneity_completeness_v_measure(labels_true, labels_pred)

(0.6666666666666669, 0.420619835714305, 0.5158037429793889)

In [ ]:
labels_pred = [0, 0, 0, 1, 2, 2]
metrics.homogeneity_completeness_v_measure(labels_true, labels_pred)

(1.0, 0.6853314789615865, 0.8132898335036762)

Fowlkes-Mallows scores

In [ ]:
from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]

In [ ]:
metrics.fowlkes_mallows_score(labels_true, labels_pred)

0.4714045207910317

In [ ]:
labels_pred = [1, 1, 0, 0, 3, 3]

metrics.fowlkes_mallows_score(labels_true, labels_pred)

0.4714045207910317

In [ ]:
labels_pred = labels_true[:]
metrics.fowlkes_mallows_score(labels_true, labels_pred)

1.0

In [ ]:
labels_true = [0, 1, 2, 0, 3, 4, 5, 1]
labels_pred = [1, 1, 0, 0, 2, 2, 2, 2]
metrics.fowlkes_mallows_score(labels_true, labels_pred)

0.0

Silhouette Coefficient

In [ ]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn import datasets
X, y = datasets.load_iris(return_X_y=True)

In [ ]:
import numpy as np
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=3, random_state=1).fit(X)
labels = kmeans_model.labels_
metrics.silhouette_score(X, labels, metric='euclidean')

0.5528190123564091

Calinski-Harabasz Index

In [ ]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn import datasets
X, y = datasets.load_iris(return_X_y=True)

In [ ]:
import numpy as np
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=3, random_state=1).fit(X)
labels = kmeans_model.labels_
metrics.calinski_harabasz_score(X, labels)

561.62775662962

Davies-Bouldin Index

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
from sklearn.cluster import KMeans
from sklearn.metrics import davies_bouldin_score
kmeans = KMeans(n_clusters=3, random_state=1).fit(X)
labels = kmeans.labels_
davies_bouldin_score(X, labels)

0.6619715465007511

Contingency Matrix

In [ ]:
from sklearn.metrics.cluster import contingency_matrix
x = ["a", "a", "a", "b", "b", "b"]
y = [0, 0, 1, 1, 2, 2]
contingency_matrix(x, y)

array([[2, 1, 0],
       [0, 1, 2]])

Pair Confusion Matrix

In [ ]:
from sklearn.metrics.cluster import pair_confusion_matrix
pair_confusion_matrix([0, 0, 1, 1], [0, 0, 1, 1])

array([[8, 0],
       [0, 4]])

In [ ]:
pair_confusion_matrix([0, 0, 1, 1], [1, 1, 0, 0])

array([[8, 0],
       [0, 4]])

In [ ]:
pair_confusion_matrix([0, 0, 1, 2], [0, 0, 1, 1])

array([[8, 2],
       [0, 2]])

In [ ]:
pair_confusion_matrix([0, 0, 1, 1], [0, 0, 1, 2])


array([[8, 0],
       [2, 2]])

In [ ]:
pair_confusion_matrix([0, 0, 0, 0], [0, 1, 2, 3])


array([[ 0,  0],
       [12,  0]])